OpenAssistant instruction data
PygmalionAI/data-toolbox pull request #18
Opened 2023-05-11 20:57 UTC by TearGosling

Rather basic implementation of the OpenAssistant dataset. Let me know if you've got comments.

2023-05-14 17:57 UTC, 0x000011b requested changes
I failed to test this one on my end, but already caught some stuff by looking at the code.

2023-05-14 17:57 UTC, 0x000011b commented on toolbox/datasets/oasst.py
> +def get_list_of_dicts(d):
This function is for exclusive use internal to this file, so I'd recommend renaming it to `_get_list_of_dicts` and moving it to the bottom of the file for consistency with the rest of the repo.

2023-05-14 17:57 UTC, 0x000011b commented on toolbox/datasets/oasst.py
> +    kept_languages: The list of languages in OpenAssist to keep in the final dataset. Set to None to keep all languages.
Bad copy-paste? I see that this param is a part of the `Task`, not the `Dataset`.

2023-05-14 17:57 UTC, 0x000011b commented on toolbox/datasets/oasst.py
> +                        language=conversation[0]["lang"],
I have this exact same file on my end (`2023-04-12_oasst_ready.trees.jsonl`), but this line crashes with:

```
    language=conversation[0]["lang"],
KeyError: 'lang'
```

On my machine. Did I miss something?

2023-05-14 17:57 UTC, 0x000011b commented on toolbox/tasks/oasst_instruction_following.py
> +            if self.kept_languages is not None and conversation[0]['lang'] not in self.kept_languages:
We can check `conversation.language` instead of `conversation[0]['lang']` here.

2023-05-18 03:21 UTC, TearGosling commented
Pushed some changes which hopefully resolve all these issues.

2023-08-11 04:13 UTC, TearGosling commented
Ancient PR, closing for tidying up

2023-08-11 04:13 UTC, closed without merging